
image:
  name: virtuslab/scala-cli:latest
  entrypoint: [""]

stages:
  - build
  - test

build-job:
  stage: build
  script:
    - scala compile .

test-job:
  stage: test
  script:
    - scala test .

