
stages:
  - build
  - test
  - format

build-job:
  stage: build
  script:
    - scala-cli compile .

test-job:
  stage: test
  script:
    - scala test .

format-job:
  stage: format
  script:
    - scala fmt --check .

