
image: nv323/scalacli-dafny:latest

stages:
  - build
  - test
  - format

build-job:
  stage: build
  script:
    - scala-cli compile .

test-job:
  stage: test
  script:
    - scala-cli test .

format-job:
  stage: format
  script:
    - scala-cli fmt --check .
