from pygments.lexer import RegexLexer, words
from pygments.token import *

KEYWORDS = ('abstract',
      'allocated',
      'as',
      'assert',
      'assume',
      'bool',
      'break',
      'by',
      'calc',
      'case',
      'class',
      'codatatype',
      'const',
      'constructor',
      'continue',
      'datatype',
      'decreases',
      'else',
      'ensures',
      'exists',
      'expect',
      'export',
      'extends',
      'false',
      'for',
      'forall',
      'fresh',
      'function',
      'ghost',
      'if',
      'imap',
      'import',
      'in',
      'include',
      'invariant',
      'is',
      'iset',
      'iterator',
      'label',
      'lemma',
      'map',
      'match',
      'method',
      'modifies',
      'modify',
      'module',
      'multiset',
      'nameonly',
      'new',
      'newtype',
      'null',
      'object',
      'object?',
      'old',
      'opaque',
      'opened',
      'ORDINAL',
      'predicate',
      'print',
      'provides',
      'reads',
      'refines',
      'requires',
      'return',
      'returns',
      'reveal',
      'reveals',
      'static',
      'string',
      'then',
      'this',
      'trait',
      'true',
      'twostate',
      'type',
      'unchanged',
      'var',
      'while',
      'witness',
      'yield',
      'yields')

KEYWORD_TYPES = ('char', 'seq', 'set', 'real', 'nat', 'int')

class CustomLexer(RegexLexer):
    name = 'Dafny'
    filenames = ['*.dfy']

    tokens = {
        'root': [
            (r"//.*?$", Comment.Singleline),
            (words(KEYWORDS, suffix=r'\b'), Keyword),
            (words(KEYWORD_TYPES, suffix=r'\b'), Keyword.Type),
            (r"\b(\d+(\.\d+)?)\b", Number),
            (r"\"[^\"]*\"", String),
            (r"\b[A-Za-z_?\'][A-Za-z0-9_?\']*(?=\(|\<)\b", Name.Function),
            (r"\b[A-Za-z_?\'][A-Za-z0-9_?\']*\b", Name),
        ]
    }
